# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webteam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('slug', models.SlugField(max_length=200, verbose_name='Адрес в url')),
                ('img', models.ImageField(blank=True, upload_to='articles/')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('slug', webteam.models.UniqueSlug(max_length=200, verbose_name='Адрес в url')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webteam.Categories', verbose_name='Категория'),
        ),
    ]
